### ISSUE TITLE
TypeError: Cannot assign to read only property 'baseURI' of object '#<XMLDocument>'

### ISSUE THREAD

**Issue by TheodoraPetkova** [dokieli/dokieli#251] opened 2018-10-19 01:40 UTC
Hey there!
I am trying to write my first post in Solid :) and opening a dokieli document I can't write in it.
Here's the resource - it is public - https://teodora.solid.community/public/A%20My%20first%20blog%20post%20on%20Solid/
And here's the error I get. 
Outline.expand: Unable to fetch <https://teodora.solid.community/public/A%20My%20first%20blog%20post%20on%20Solid/index.html>: Failed to load  <https://teodora.solid.community/public/A%20My%20first%20blog%20post%20on%20Solid/index.html> Fetcher: Error trying to parse <https://teodora.solid.community/public/A%20My%20first%20blog%20post%20on%20Solid/index.html> as RDFa:
TypeError: Cannot assign to read only property 'baseURI' of object '#<XMLDocument>':
TypeError: Cannot assign to read only property 'baseURI' of object '#<XMLDocument>'
    at value (https://teodora.solid.community/common/js/mashlib.min.js:8:312433)
    at t.value (https://teodora.solid.community/common/js/mashlib.min.js:8:260340)
    at t.value (https://teodora.solid.community/common/js/mashlib.min.js:8:262739)
    at https://teodora.solid.community/common/js/mashlib.min.js:8:277570

Any help/hint is appreciated. Thanks!

**Comment by csarven** [comment] 2018-10-19 08:50
Thanks for raising.

This issue seems to be a duplicate of https://github.com/solid/solid-panes/issues/40 - it doesn't originate at dokieli.

Would you agree to close it here?

PS: I suggest to write to /foo as opposed to / . The former is generally interpreted as a "file" whereas the latter as a "directory".

**Closed as completed** 2024-04-23 12:45 UTC
Labels: status: Commenter Timeout
