### ISSUE TITLE
Using dokieli to read and write documents

### ISSUE THREAD

**Issue by melvincarvalho** [dokieli/dokieli#40] opened 2015-12-15 07:10 UTC
It's not immediately clear (at least to me) how to use dokieli to read and write documents either from the README or from the website.

Could a short guide be written.

**Comment by csarven** [comment] 2015-12-15 07:39
Thanks @melvincarvalho . Trying to improve that. Duplicate of #36

**Closed as completed by csarven** 2015-12-15 07:39 UTC
