### ISSUE TITLE
Not able to format text as title tags with toolbar

### ISSUE THREAD

**Issue by megoth** [dokieli/dokieli#291] opened 2019-08-09 11:11 UTC
I'm not able to set titles using the toolbar shown when text is selected. All other tools seem to work, but not `h2`, `h3`, and `h4`.

I get the following error in the console:

```
dokieli.js:5875 Uncaught TypeError: Cannot read property 'length' of undefined
    at n.handleClick (dokieli.js:5875)
```

**Comment by csarven** [comment] 2019-08-09 11:14
Sorry about this. It needs some refactoring around MediumEditor. This issue is a duplicate of https://github.com/linkeddata/dokieli/issues/203 . Closing if you don't mind.

**Closed as completed by csarven** 2019-08-09 11:14 UTC
