### ISSUE TITLE
No Firefox Add-on

### ISSUE THREAD

**Issue by rat10** [dokieli/dokieli#239] opened 2018-05-13 20:49 UTC
The links to the Firefox Add-on are broken and search in the Firefox Add-on repositiry for "Dokieli" finds no editor. I'm using Firefox 60 on MacOS.

**Comment by csarven** [comment] 2018-05-14 04:27
Thanks for reporting.

I think this is a duplicate of https://github.com/linkeddata/dokieli/issues/231 . Please see my response in the comments. Basically possible to install it in Firefox but just not available from AMO ( https://addons.mozilla.org ) yet.

We need to have a closer look at some of the things mentioned here: https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews

The last review mentioned:

>The following information is needed to complete your review:
>1) This version contains obfuscated, minified, concatenated or otherwise machine-generated code. Please provide the original sources, together with instructions on how to generate the final XPI. Source code must be provided as an archive and uploaded using the source code upload field, which can be done during submission or on the version page in the developer hub.
>Please read through the instructions at https://developer.mozilla.org/en-US/Add-ons/Source_Code_Submission. If sources have not been provided within 7 days, this version will be rejected and removed from our queues.
>More Information: https://blog.mozilla.org/addons/2016/04/05/improved-review-time-with-links-to-sources/
>Established libraries (eg: JQuery, bootstrap) do not require the inclusion of their sources.

and

>The following information is needed to complete your review:
>1) Please upload the sources as a zip file on addons.mozilla.org, a link to a github repository is unfortunately not enough.
>https://developer.mozilla.org/en-US/Add-ons/Source_Code_Submission

We didn't act quickly so it was taken down.

If you want to give this a shot so that dokieli core is AMO (mozilla WebExtension) friendly, that'd really be a great contribution. Maybe create specific issues eg. DOM building instead of innerHTML, towards that end, and we can close this issue? It wasn't clear to me whether that's absolutely required (for all JS involved) or only for the extension's scripts. The last review didn't mention that as an issue - libraries like MediumEditor use it but that wasn't mentioned as an issue for some reason. For dokieli's core scritps, that should be straight forward, but more problematic (and maybe even not really resolvable) for the additional libraries.

**Comment by rat10** [comment] 2018-05-14 08:04
Thanks for the quick reply and you're right, it's a duplicate - sorry! Maybe comment the links accordingly as broken links quickly give an impression of staleness. Dokieli seems like a great project but at least for the coming months I can't commit to anything.

**Comment by AdrianSkar** [comment] 2022-01-10 10:26
Hi! Is there any way to install it without being temporary?

**Comment by maphew** [comment] 2024-09-27 20:50
the link for the non-existant firefox add-on in the store is still in the docs. Shouldn't it be removed? having such an old broken link makes the project look bad

**Closed as completed** 2024-09-28 07:39 UTC
Labels: browser-extension

**Comment by csarven** [comment] 2024-09-28 07:44
@maphew Thanks for the nudge. I agree with you and everyone. This has been stale for a long time. I think it is best to just only advertise how it can be loaded from a local machine for the time being. We'll revisit how the extension is available from third-party stores.

I've updated the instructions in https://dokie.li/docs#web-extension and https://github.com/linkeddata/dokieli/blob/main/README.md#use

If there are essentials details that's not captured, please let me know or PR is welcome. That includes instructions for category of browsers that's not currently listed (which is Firefox and Chromium-based). I haven't tested much beyond that.
