### ISSUE TITLE
Addon link for firefox shows error

### ISSUE THREAD

**Issue by baali** [dokieli/dokieli#301] opened 2020-04-15 06:48 UTC
Addon URL: https://addons.mozilla.org/en-US/firefox/addon/dokieli/ says:

>  Oops! We can’t find that page

This url for is mentioned [here](https://github.com/linkeddata/dokieli/blob/master/docs#L694) in the docs.

**Comment by csarven** [comment] 2020-04-15 07:41
Thanks for reporting. I think this is a duplicate of #239 .

**Closed as completed by csarven** 2020-04-15 07:41 UTC
Labels: browser-extension
