### ISSUE TITLE
OpenID Connect (OIDC) Login Regression 

### ISSUE THREAD

**Issue by kidehen** [dokieli/dokieli#258] opened 2018-11-09 22:01 UTC
Using the latest and greatest dokie.li release from the Chrome Store, I am no longer able to authenticate using OpenID Connect (OIDC). 

Steps to recreate the problem:
1. Goto a page of interest
2. Click on Extension Icon in Browser Toolbar
3. Click "Sign in" button
4. Pick you preferred Idp from "popup.html"

At this point, rather than being logged in you are returned to the beginning of the OIDC login sequence.
<img width="1268" alt="screen shot 2018-11-09 at 4 59 56 pm" src="https://user-images.githubusercontent.com/1541745/48290463-f688cb00-e440-11e8-8b05-f36331230150.png">

This doesn't happen with my locally built variant which I run concurrently with the live edition.

**Comment by csarven** [comment] 2018-11-09 22:13
Do you have an extension that's blocking requests eg Privacy Badger or uBlock Origin?

**Comment by csarven** [comment] 2018-11-11 10:42
Please confirm what happens in Privacy mode (and other extensions that may be blocking network are turned off) for either of the following:
* v0.3.26 in Chrome store
* local install of what's currently in GitHub repo (also marked as v0.3.26)

I've tried tested with both instances on https://github.com/kidehen and I am unable to reproduce.

**Comment by kidehen** [comment] 2018-11-11 16:30
@csarven ,

Confirming that I can now login once again using OIDC, following the most recent update.

**Comment by kidehen** [comment] 2018-11-11 16:30
Fix verified.

**Closed as completed** 2018-11-11 16:30 UTC
